services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: meu_banco
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
